ShibaApp/urls.py
from django.urls import path
from ShibaApp import views

app_name = 'ShibaApp'

urlpatterns = [
    path('profile/', views.user_profile, name='user_profile'),
    path('photos/', views.user_photos, name='user_photos'),
    path('register/', views.newuser_register, name='newuser_register'),
    path('friends/', views.user_friends, name='user_friends'),
    path('login/',views.user_login,name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
]

ShibaNet/urls.py
from django.contrib import admin
from django.urls import path, include
from ShibaApp import views
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('', include('ShibaApp.urls')),
]

ShibaApp/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User

# Create your models here.
class ShibaUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    profile_bio = models.CharField(max_length=500)

    def __str__(self):
        return self.user.username

ShibaApp/forms.py
from django import forms
from ShibaApp.models import ShibaUser
from django.contrib.auth.models import User

class ShibaUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username','email','password']
        help_texts = {
            'username': '',
        }

class ShibaProfileForm(forms.ModelForm):
    class Meta:
        model = ShibaUser
        fields = ['profile_pic','profile_bio']

ShibaApp/views.py
from django.shortcuts import render
from ShibaApp.forms import ShibaUserForm, ShibaProfileForm
# from ShibaApp.models import ShibaUser
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request, 'ShibaApp/index.html')

@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))



def user_profile(request):
    return render(request, 'ShibaApp/profile.html')

def user_photos(request):
    return render(request, 'ShibaApp/photos.html')

def newuser_register(request):
    registered = False

    if request.method == 'POST':
        user_form = ShibaUserForm(data=request.POST)
        profile_form = ShibaProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            print(request.FILES)

            profile.save()
            registered = True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = ShibaUserForm()
        profile_form = ShibaProfileForm()



    return render(request, 'ShibaApp/register.html', {'ShibaUserForm':user_form,'ShibaProfileForm':profile_form, "Registered":registered})

def user_login(request):

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('ShibaApp:user_profile'))
            else:
                my_dict = {'user':username}
                return render(request,'login_failed.html',context=my_dict)
        else:
            return HttpResponse("Invalid login details supplied.")
    else:

        return render(request, 'ShibaApp/login.html')

def user_friends(request):
    return render(request, 'ShibaApp/friends.html')

templates/ShibaApp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <title>{% block title %} Base Page {% endblock %}</title>

    <!-- Bootstrap and CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/shibastyle.css' %}">


  </head>


  <body>

    <!-- Navbar -->
    <nav class='navbar fixed-top navbar-dark navbar-expand-sm'>
      <a href="{% url 'index' %}" class='navbar-brand'><img src="{% static 'images/shiba_icon_transparent.png' %}" width=50px; height=50px alt=""> Shiba Network</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Alterna navegação">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="{% url 'ShibaApp:user_profile'%}" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Hello, {{ user.username}}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'ShibaApp:user_profile'%}">Profile</a>
            <a class="dropdown-item" href="{% url 'ShibaApp:user_photos'%}">Photos</a>
            <a class="dropdown-item" href="{% url 'ShibaApp:user_friends'%}">Friends</a>
            <!-- Unused itens
            <a class="dropdown-item" href="#">Link 3</a>
            <a class="dropdown-item" href="#">Link 4</a> -->
          </div>
        </li>
        {% endif %}
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ShibaApp:user_logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ShibaApp:user_login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ShibaApp:newuser_register' %}">Register</a>
        </li>
        {% endif %}
      </ul>

    </div>
  </nav>
<div class="container">

  {% block body_block %}
  <div class="jumbotron">
    <h1 class='text-center'>Django Base</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  </div>
<div class="jumbotron">
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</h2>
  <h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</h2>
  <h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</h2>
  <h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</h2>

</div>
{% endblock %}
</div>

<!-- JS and JQuery -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  </body>
</html>

templates/ShibaApp/friends.html
{% extends 'ShibaApp/base.html' %}
{% block title %} My Friends {% endblock %}
  {% block body_block %}
  <h1>Friends Page</h1>
  {% endblock %}

templates/ShibaApp/index.html
{% extends 'ShibaApp/base.html' %}
{% block title %} Welcome to the Shiba Network! {% endblock %}
  {% block body_block %}
  <h1>Django</h1>
  {% endblock %}

templates/ShibaApp/login.html
{% extends 'ShibaApp/base.html' %}
{% block title %} Login to the Shiba Network! {% endblock %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" style="margin=">
      <span class='text-center'><h1>Please Login</h1></span>

        <form class="form-inline" action="{% url 'ShibaApp:user_login' %}" method="POST">

            {% csrf_token %}
            <!-- # A more "HTML" way of creating the login form# -->
              <!-- <div class="flex-fill"> -->
              <div class="form-row flex-fill">
                  <div class="input-group mb-2 mr-2 ml-lg-auto">
                    <div class="input-group-prepend">
                      <div class="input-group-text">@</div>
                    </div>
                    <input type="text" name="username" class="form-control" placeholder="Username">
                  </div>

                  <input type="password" name="password" class="form-control mb-2 mr-4" placeholder="Password">

                <input type="submit" class="btn btn-outline-dark mr-lg-auto" name="" value="Login">
              </div>
              <!-- </div> -->





        </form>

    </div>
  </div>

  {% endblock %}

templates/ShibaApp/login_failed.html
{% extends 'ShibaApp/base.html' %}
{% block title %} Login has failed {% endblock %}
  {% block body_block %}
  <h1>Failed Login</h1>
  <p>{{ user }} is not an active account </p> 
  {% endblock %}

templates/ShibaApp/photos.html
{% extends 'ShibaApp/base.html' %}
{% block title %} My Photos {% endblock %}
  {% block body_block %}
  <h1>Photos Page</h1>
  {% endblock %}

templates/ShibaApp/profile.html
{% extends 'ShibaApp/base.html' %}
{% block title %} My Profile {% endblock %}
  {% block body_block %}
  <h1>My Profile Page</h1>
  {% endblock %}

templates/ShibaApp/register.html
{% extends 'ShibaApp/base.html' %}
{% block title %} Register now to the Shiba Network! {% endblock %}
  {% block body_block %}


  {% if Registered %}
    <meta http-equiv="refresh" content="3;url={% url 'ShibaApp:user_profile' %}" />
    <h1>Thank you for registering!</h1>
    <h3>You will be redirect in a few seconds...</h3>
  {% else %}
    <div class="container">
      <div class="jumbotron text-center">
        <h1>Register Page</h1>
        <!-- enctype="multipart/form-data"
        No characters are encoded. This value is required when forms have FILE UPLOAD CONTROL -->
        <form enctype="multipart/form-data" method="POST">
          <div class="form-group">
            {% csrf_token %}
            {{ ShibaUserForm.as_p }}
            {{ ShibaProfileForm.as_p}}
            <input type="submit" name="" value="Register">
          </div>
        </form>
      </div>

    </div>

  {% endif %}





  {% endblock %}